config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  # get 'tedtalks/index'
  # get 'tedtalks/show'

  # root_path
  root to: 'tedtalks#index'

  # about page path
  get 'about', to: 'pages#about', as: 'about'

  # tedtalks - index and show pages
  resources :tedtalks, only: [:index, :show] do
    collection do
      get 'results'
    end
  end

  # speakers path - index and show page
  # get '/speakers', to: 'speakers#index', as: 'speaker'
  # get '/speakers/:id', to: 'speakers#show'
  resources :speakers, only: [:index, :show], as: 'speakers'

  # tags path - index and show pages
  resources :tags, only: [:index, :show], as: 'tags'

  # get 'search/results', to: 'search#results' as: 'search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :tag
  belongs_to :tedtalk
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  has_many :tedtalks, dependent: :destroy

  validates :name, presence:true, uniqueness:true
  paginates_per 10
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :categories
  has_many :tedtalks, through: :categories

  validates :name, presence:true, uniqueness:true
end

app/models/tedtalk.rb
class Tedtalk < ApplicationRecord
  belongs_to :speaker
  has_many :categories
  has_many :tags, through: :categories

  validates :title, :description, :url, presence: true
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def tags
    @tags = Tag.all
  end

  helper_method :tags
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @projects = Project.search(params[:search])
  end

  def search
    @tedtalks = Tedtalk.where('title LIKE ?', "%#{params[:query]}%")
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def index
    @speakers = Speaker.order(:name).page(params[:page])
  end

  def show
    @speaker = Speaker.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/tedtalks_controller.rb
class TedtalksController < ApplicationController
  def index
    # @tedtalks = Tedtalk.all
    @tedtalks = Tedtalk.order(views: :desc).page(params[:page])
  end

  def show
    @tedtalk = Tedtalk.find(params[:id])
  end

  def results
    @tedtalk_results = Tedtalk.where('title LIKE ?', "%#{params[:query]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tedtalks_helper.rb
module TedtalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TedTalks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Ted Talks', root_path, class: "navbar-brand mb-0 h1" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %><span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <%= link_to 'Speakers', speakers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% tags.each do |tag| %>
                <%= link_to tag.name.strip.gsub("'","").capitalize, tag, class: "dropdown-item"  %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: "nav-link" %>
          </li>
        </ul>
        <%= form_tag(results_tedtalks_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="query" aria-label="Search">
          <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
        <% end %>
      </div>
    </nav>

    <div id="main-container" class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/pages/about.html.erb
<div class=" p-3 mb-5">

</div>

<div class="card">
  <h5 class="card-header">About Dataset</h5>
  <div class="card-body">
    <h5 class="card-title">Data Information</h5>
    <p class="card-text text-justify">This datasets contain information about all audio-video recordings of TED Talks uploaded to the official TED.com website until September 21st, 2017. The TED main dataset contains information about all talks including titles, descriptions, speakers, number of views and tags for the ted talks.</p>
    <%= link_to 'Database Structure', "/erd.pdf", target: "_blank", class: "btn btn-primary" %>
  </div>
</div>

app/views/speakers/index.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
  <h3>Available Speakers</h3>
</div>

<div class="col align-self-start">
<%= paginate @speakers, theme: 'twitter-bootstrap-4' %>
</div>

<div class="container">
  <div class="list-group">
    <% @speakers.each do |speaker| %>
      <%= link_to speaker.name, speaker, class: "list-group-item list-group-item-action list-group-item-light font-weight-bold" %>
    <% end %>
  </div>
</div>

app/views/speakers/show.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
  <h3>Speaker - <span class="text-info font-weight-bold"> <%= @speaker.name %> </span></h3>
</div>

<% @speaker.tedtalks.each do |talk| %>
  <div class="alert alert-info" role="alert">
    <h4 class="alert-heading"><%= link_to talk.title, talk %></h4>
    <hr>
    <p class="text-justify"><%= talk.description %></p>
  </div>
<% end %>

app/views/tags/index.html.erb
<h2>Available Ted Talk Categories </h2>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <pre>
        <b><%= link_to tag.name.strip.gsub("'","").capitalize, tag %></b>
      </pre>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
  <h3 class="text-info font-weight-bold"> <%= @tag.name.strip.gsub("'","").capitalize %></h3>
</div>

<% @tag.tedtalks.each do |talk| %>
  <div class="alert alert-info" role="alert">
    <h4 class="alert-heading"><%= link_to talk.title, talk %></h4>
    <hr>
    <p class="text-justify"><%= talk.description %></p>
  </div>
<% end %>

app/views/tedtalks/index.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
  <h3 class="text-info font-weight-bold">Ted Talks</h3>
</div>

<div class="col align-self-start">
<%= paginate @tedtalks, theme: 'twitter-bootstrap-4' %>
</div>

<div class="container">
<% @tedtalks.each do |talk| %>
  <div class="alert alert-info" role="alert">
    <h4 class="alert-heading"><%= link_to talk.title, talk %></h4>
    <hr>
    <p class="text-justify"><%= talk.description %></p>
  </div>
<% end %>
</div>

<div class="col align-self-start">
<%= paginate @tedtalks, theme: 'twitter-bootstrap-4' %>
</div>

app/views/tedtalks/results.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
  <h3 class="text-info"> Found <%= pluralize @tedtalk_results.count, 'Ted talk' %>  with related search.</h3>
</div>

<% @tedtalk_results.each do |talk| %>
  <div class="alert alert-info" role="alert">
    <h4 class="alert-heading"><%= link_to talk.title, talk %></h4>
    <hr>
    <p class="text-justify"><%= talk.description %></p>
  </div>
<% end %>

app/views/tedtalks/show.html.erb
<div class="shadow-lg p-3 mb-5 bg-light rounded">
    <h3><%= @tedtalk.title %></h3>
  </div>

<div class="alert alert-info" role="alert">
    <h4 class="alert-heading"><%= @tedtalk.title %></h4>
    <hr>
    <p class="text-justify"><%= @tedtalk.description %></p>
    <hr>
    <p><%= link_to @tedtalk.speaker.name, @tedtalk.speaker %></p>
    <hr>
    <p><%= link_to @tedtalk.url, @tedtalk.url %></p>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="<%= @tedtalk.url %>" allowfullscreen></iframe>
    </div>
    <hr>
    <p><% @tedtalk.tags.each do |tag| %>
        <%= link_to tag.name.strip.gsub("'","").capitalize, tag, class: "btn btn-outline-primary"  %>
      <% end %>
    </p>
    <hr>
    <p>Views: <%= @tedtalk.views %></p>
  </div>